<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../.resources/report.css" type="text/css"/><link rel="shortcut icon" href="../.resources/report.gif" type="image/gif"/><title>ExpectException.java</title><link rel="stylesheet" href="../.resources/prettify.css" type="text/css"/><script type="text/javascript" src="../.resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../.sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">Junit-r4.11</a> &gt; <a href="index.source.html" class="el_package">org.junit.internal.runners.statements</a> &gt; <span class="el_source">ExpectException.java</span></div><h1>ExpectException.java</h1><pre class="source lang-java linenums">package org.junit.internal.runners.statements;

import org.junit.internal.AssumptionViolatedException;
import org.junit.runners.model.Statement;

public class ExpectException extends Statement {
    private Statement fNext;
    private final Class&lt;? extends Throwable&gt; fExpected;

<span class="fc" id="L10">    public ExpectException(Statement next, Class&lt;? extends Throwable&gt; expected) {</span>
<span class="fc" id="L11">        fNext = next;</span>
<span class="fc" id="L12">        fExpected = expected;</span>
<span class="fc" id="L13">    }</span>

    @Override
    public void evaluate() throws Exception {
<span class="fc" id="L17">        boolean complete = false;</span>
        try {
<span class="fc" id="L19">            fNext.evaluate();</span>
<span class="fc" id="L20">            complete = true;</span>
<span class="nc" id="L21">        } catch (AssumptionViolatedException e) {</span>
<span class="nc" id="L22">            throw e;</span>
<span class="fc" id="L23">        } catch (Throwable e) {</span>
<span class="fc bfc" id="L24" title="All 2 branches covered.">            if (!fExpected.isAssignableFrom(e.getClass())) {</span>
<span class="fc" id="L25">                String message = &quot;Unexpected exception, expected&lt;&quot;</span>
                        + fExpected.getName() + &quot;&gt; but was&lt;&quot;
                        + e.getClass().getName() + &quot;&gt;&quot;;
<span class="fc" id="L28">                throw new Exception(message, e);</span>
            }
<span class="fc" id="L30">        }</span>
<span class="fc bfc" id="L31" title="All 2 branches covered.">        if (complete) {</span>
<span class="fc" id="L32">            throw new AssertionError(&quot;Expected exception: &quot;</span>
                    + fExpected.getName());
        }
<span class="fc" id="L35">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.eclemma.org/jacoco">JaCoCo</a> 0.7.0.201403182114</span></div></body></html>